### ISSUE TITLE
класс App, константы, валидатор

### ISSUE THREAD

**Issue by a0z9** [AndesTechConsulting5/JavaSE-Day05-HomeWork#10]
1. закомментировать / убрать  public static Account в классе App..
2. как внести функционал разного типа счетов в проверки в классе Account?
С учетом того, что проверочные константы различаются для разных типов счетов.
3. чем оправдано вынесение функционала для проверки при выдаче кредита в отдельный (не внутренний) класс CreditCustomerValidator?

**Comment by ultraya2** [comment]
1. удалил
2. вынес проверки в конкретные классы
3. сделал приватным статическим вложенным классом
